# codemagic.yaml
# For more information, check out:
# - https://docs.codemagic.io/yaml/yaml-conventions/
# - https://docs.codemagic.io/yaml/building-a-react-native-app/

workflows:
  bifold-android-build:
    name: Bifold Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2 # Recommended for React Native
    environment:
      vars:
        PACKAGE_NAME: "com.ariesbifold" # <-- Update with Bifold's actual package name
        ANDROID_SDK_ROOT: /opt/android-sdk # Codemagic's default SDK location
        MEDIATOR_URL: "https://public.mediator.indiciotech.io?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiMDVlYzM5NDItYTEyOS00YWE3LWEzZDQtYTJmNDgwYzNjZThhIiwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwczovL3B1YmxpYy5tZWRpYXRvci5pbmRpY2lvdGVjaC5peSIsICJyZWNpcGllbnRLZXlzIjogWyJDc2dIQVpxSktuWlRmc3h0MmRIR3JjN3U2M3ljeFlEZ25RdEZMeFhpeDIzYiJdLCAibGFiZWwiOiAiSW5kaWNpbyBQdWJsaWMgTWVkaWF0b3IifQ=="
      node: v18.20.6 # As per the Bifold guide
    scripts:
      - name: Install npm dependencies
        script: yarn install
      - name: Build the app (transpile packages)
        script: yarn run build
      - name: Set Android SDK location (if needed)
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/samples/app/android/local.properties"
      - name: Build Android release APK
        script: |
          cd samples/app/android
          ./gradlew assembleRelease
    artifacts:
      - samples/app/android/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - your_email@example.com # Add your email to receive build status
        notify:
          success: true
          failure: true
